#Task 3: Feature Engineering
This task will focus on creating new features from existing columns to improve understanding and preparing the dataset for modeling.

##Import libraries

In [1]:
import pandas as pd

## Load datset

In [2]:
df = pd.read_csv("/content/Dataset .csv")
df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

## Length of Restaurant Name

Creating a new feature based on the number of characters
in the restaurant name.

In [3]:
df['Restaurant_Name_Length'] = df['Restaurant Name'].str.len()
df[['Restaurant Name', 'Restaurant_Name_Length']].head()

          Restaurant Name  Restaurant_Name_Length
0        Le Petit Souffle                      16
1        Izakaya Kikufuji                      16
2  Heat - Edsa Shangri-La                      22
3                    Ooma                       4
4             Sambo Kojin                      11

As per the observation length of restaurants name varies and can be useful for analysis.

## Length of Restaurant Address

Creating a feature based on the length of the restaurant address.

In [4]:
df['Address_Length'] = df['Address'].str.len()
df[['Address', 'Address_Length']].head()

                                             Address  Address_Length
0  Third Floor, Century City Mall, Kalayaan Avenu...              71
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...              67
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...              56
3  Third Floor, Mega Fashion Hall, SM Megamall, O...              70
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...              64

As per the observation the address length provides information about how detailed the location is.

## Encoding Table Booking Feature

In [5]:
df['Table_Booking_Flag'] = df['Has Table booking'].map({'Yes': 1, 'No': 0})
df[['Has Table booking', 'Table_Booking_Flag']].head()

  Has Table booking  Table_Booking_Flag
0               Yes                   1
1               Yes                   1
2               Yes                   1
3                No                   0
4               Yes                   1

As per the observation table booking availability is now represented as a binary feature.

## Encoding Online Delivery Feature

In [6]:
df['Online_Delivery_Flag'] = df['Has Online delivery'].map({'Yes': 1, 'No': 0})
df[['Has Online delivery', 'Online_Delivery_Flag']].head()

  Has Online delivery  Online_Delivery_Flag
0                  No                     0
1                  No                     0
2                  No                     0
3                  No                     0
4                  No                     0

As per the observation online delivery availability has been converted into a numeric format.

## Checking Newly Created Features

In [7]:
df[['Restaurant_Name_Length', 'Address_Length',
    'Table_Booking_Flag', 'Online_Delivery_Flag']].describe()

,Restaurant_Name_Length,Address_Length,Table_Booking_Flag,Online_Delivery_Flag
count,9551.000000,9551.000000,9551.000000,9551.000000
mean,15.164171,53.536698,0.121244,0.256622
std,6.858392,17.122035,0.326428,0.436792
min,2.000000,13.000000,0.000000,0.000000
25%,10.000000,41.000000,0.000000,0.000000
50%,14.000000,52.000000,0.000000,0.000000
75%,19.000000,64.000000,0.000000,1.000000
max,54.000000,132.000000,1.000000,1.000000

## Conclusion

New features were successfully created from existing column.
Text-based features like name and address length were excited.
Categorical variables for table booking and online delivery were encoded into numeric format for further analysis or modeling.